add HW 06
babenko-alex-pdffiller/prjctr-golang pull request #1
Opened 2024-08-29 20:27 UTC by babenko-alex-pdffiller

2024-08-30 17:45 UTC, alexandear requested changes
Чи можемо написати тести?

2024-08-30 17:45 UTC, alexandear commented on gocourse06/homework.go
> +	fmt.Scanln()
Чи можемо використати [sync.WaitGroup](https://pkg.go.dev/sync#WaitGroup) для синхронізації горутин?

2024-08-30 17:45 UTC, alexandear commented on gocourse06/homework.go
> +	for i := range [5]int{} {
Ось так має працювати:
```suggestion
	for i := range 5 {
```

2024-08-30 17:45 UTC, alexandear commented on gocourse06/homework.go
> +	ch <- *feeder
Трішки спростимо:
```suggestion
func collectFeedersData(feeder Feeder, ch chan<- Feeder) {
	ch <- feeder
```

2024-08-31 14:44 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +	for i := range [5]int{} {
замінив

2024-08-31 14:56 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +	fmt.Scanln()
додав використання

2024-08-31 14:58 UTC, babenko-alex-pdffiller commented
> Чи можемо написати тести?

так, обов'язково, просто я не встиг вчасно

2024-09-03 16:41 UTC, alexandear requested changes

2024-09-03 16:41 UTC, alexandear commented on gocourse06/homework.go
> +			fmt.Printf("Received Aminal data: %+v\n", status)
Помилочка:
```suggestion
			fmt.Printf("Received Animal data: %+v\n", status)
```

2024-09-03 16:41 UTC, alexandear commented on gocourse06/homework.go
> +	close(feedersChannel)
Щось зміниться, якщо ми видалимо ці рядки? Чи дійсно нам потрібно закривати канали?

https://gobyexample.com/closing-channels
https://go.dev/tour/concurrency/4

2024-09-03 16:41 UTC, alexandear commented on gocourse06/homework.go
> +func getAnimals() [5]Animal {
Краще підходить назва `generateAnimals`.

2024-09-03 16:41 UTC, alexandear commented on gocourse06/homework.go
> +func getCages() [5]Cage {
Тут напевно також підходить `generateCages`.

2024-09-03 16:41 UTC, alexandear commented on gocourse06/homework.go
> +func getFeeders() [5]Feeder {
І ось тут `generateFeeders`.

2024-09-03 16:41 UTC, alexandear commented on gocourse06/homework.go
> +	time.Sleep(time.Second * time.Duration(rand.IntN(3)+1))
Можемо передавати `timeout` як параметр і в тестах використовувати `timeout == 0` замість `mockCollectCagesData`?

2024-09-04 20:05 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +	close(feedersChannel)
необов'зково, паніки не буде, але ж нічого погано не станеться якщо їх закрити явно

2024-09-05 11:53 UTC, alexandear commented on gocourse06/homework.go
> +	close(feedersChannel)
Канали, на відміну від файлів, закривати не обов'язково.

2024-09-05 12:00 UTC, alexandear requested changes

2024-09-05 12:00 UTC, alexandear commented on gocourse06/homework.go
> +	}()
Здається, можна обійтися без горутини:
```suggestion
	for feeder := range feedersChannel {
		fmt.Printf("Feeder #%d is full %t\n", feeder.ID, feeder.IsFull)
	}
```
Горутина - хоч і легенька, але все одно навантажує ресурси. Тому якщо десь можна обійтися без горутини, то краще обходитися.

Пропоную прочитати статтю ["Горутинова спокуса. Приклади використання горутин, де вони насправді зайві"](https://dou.ua/forums/topic/31777/), де наведено інші приклади зайвих горутин.

2024-09-05 12:00 UTC, alexandear commented on gocourse06/homework.go
> +	ch <- *animal
В принципі, ось так має працювати і трішки легше читається:
```suggestion
var collectAnimalsData = func(animal Animal, ch chan<- Animal, timeout time.Duration) {
	ch <- animal
```

2024-09-05 12:00 UTC, alexandear commented on gocourse06/homework.go
> +	ch <- *cage
В принципі, ось так має працювати і трішки легше читається:

```suggestion
var collectCagesData = func(cage Cage, ch chan<- Cage, timeout time.Duration) {
	ch <- cage
```

2024-09-05 12:00 UTC, alexandear commented on gocourse06/homework.go
> +	time.Sleep(time.Second * timeout)
Тут помилка - перемноження duration: секунда * timeout. Підозрюю, що треба ось так:
```suggestion
	time.Sleep(timeout)
```

Ось тут деталі https://github.com/charithe/durationcheck/blob/master/README.md

2024-09-05 12:00 UTC, alexandear commented on gocourse06/homework.go
> +	time.Sleep(time.Second * timeout)
В інших функціях те саме.

2024-09-05 17:24 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +	}()
без нього видає помилку
`fatal error: all goroutines are asleep - deadlock!`

2024-09-06 13:25 UTC, alexandear requested changes

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +		}(animal)
В нас використовується Go 1.23, тому можна спростити:
```suggestion
		go func() {
			defer wg.Done()
			collectAnimalsData(&animal, animalsChannel, time.Duration(rand.IntN(5)))
		}()
```

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +		}(cage)
В нас використовується Go 1.23, тому можна спростити:

```suggestion
		go func() {
			defer wg.Done()
			collectCagesData(&cage, cagesChannel, time.Duration(rand.IntN(5)))
		}()
```

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +	}()
Дякую, що перевірив.

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +	time.Sleep(time.Second * timeout)
Не було виправлено.

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +	ch <- *cage
теж не було виправлено

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +			collectAnimalsData(animal, animalsChannel, time.Duration(rand.IntN(5)))
`time.Duration(rand.IntN(5))` - це від 0 до 4 наносекунд. Це і малось на увазі? Раніше тут були мілісекунди.

> A Duration represents the elapsed time between two instants as an int64 nanosecond count. The representation limits the largest representable duration to approximately 290 years.
Раджу глянути документацію https://pkg.go.dev/time#Duration

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +		go func(animal Animal) {
Ось це вже не потрібно, бо в нас Go 1.23.
```suggestion
		go func() {
```

Ось тут пояснено https://go.dev/blog/go1.22#language-changes

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +		go func(animal Animal) {
Те саме для всіх інших горутин.

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +func makeCages() [5]Cage {
Краще `generate` замість `make`:
```suggestion
func generateCages() [5]Cage {
```

По суті, ми тут генеруємо рандомні клітки.

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +var collectCagesData = func(cage Cage, ch chan<- Cage, timeout time.Duration) {
Простіше:
```suggestion
func collectCagesData(cage Cage, ch chan<- Cage, timeout time.Duration) {
```

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +var collectFeedersData = func(feeder Feeder, ch chan<- Feeder, timeout time.Duration) {
Простіше:
```suggestion
func collectFeedersData(feeder Feeder, ch chan<- Feeder, timeout time.Duration) {
```

2024-09-06 13:25 UTC, alexandear commented on gocourse06/homework.go
> +func processData(wg *sync.WaitGroup) {
Здається, не все із завдання реалізовано. Або я не розумію. Можеш пояснити?

Ось завдання.

```
Моніторинг стану тварин:
Створіть горутину для кожної тварини в зоопарку.
Кожна горутина збирає дані про стан тварини (наприклад, рівень здоров'я, голод, настрій) і відправляє їх через канал до центральної системи моніторингу.

Керування доступом до вольєрів:
Імплементуйте горутину, яка контролює доступ до вольєрів, використовуючи канали для отримання запитів на відкриття/закриття.

Управління кормушками:
Розробіть горутини для управління автоматичними кормушками, які відправляють статус кормушки (порожня/повна) через канал.
```

2024-09-09 08:50 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +	ch <- *cage
так, моя провина, зробити - зробив, а запушити в репу забув, соррі, обновив

2024-09-09 08:51 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +	time.Sleep(time.Second * timeout)
те саме, див.вище

2024-09-09 09:03 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +			collectAnimalsData(animal, animalsChannel, time.Duration(rand.IntN(5)))
так, дісно, щось я поторопився...виправив

2024-09-09 09:04 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +func makeCages() [5]Cage {
спірне зауваження, ми їх створюємо з рандомними значеннями,але най буде `generate`

2024-09-09 16:02 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +var collectCagesData = func(cage Cage, ch chan<- Cage, timeout time.Duration) {
воно і так не складно, виправив

2024-09-11 18:43 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +func processData(wg *sync.WaitGroup) {
трохи змінив, здається так буде ближче до ТЗ

2024-09-12 11:34 UTC, alexandear requested changes
Залишилось одне важливе питання.

2024-09-12 11:34 UTC, alexandear commented on gocourse06/homework.go
> +	chanel chan<- bool
Тут помилка в слові `channel`. Але краще назвати по-іншому, щоб було зрозуміліше, які дані передаються по цьому каналу.

2024-09-12 11:34 UTC, alexandear commented on gocourse06/homework.go
> +	fmt.Printf("Recived Feeder status: is full %t\n", feederState)
Помилочка:
```suggestion
	fmt.Printf("Received Feeder status: is full %t\n", feederState)
```

2024-09-12 11:34 UTC, alexandear commented on gocourse06/homework.go
> +	fmt.Printf("Recived Feeder status: is full %t\n", feederState)
Одруківка:
```suggestion
	fmt.Printf("Received Feeder status: is full %t\n", feederState)
```

2024-09-12 11:34 UTC, alexandear commented on gocourse06/homework.go
> +	if cage.IsOpen == true {
Можна спростити:
```suggestion
	if cage.IsOpen {
```

2024-09-12 11:34 UTC, alexandear commented on gocourse06/homework.go
> +		cage.IsOpen = false
Здається, це присвоєння не змінює нічого. Так і задумано було?

```go
cage := <-ch        // змінна типу Cage
cage.IsOpen = false // змінили локальну змінну cage, далі вона нікуди не йде
```

2024-09-12 11:41 UTC, alexandear commented on gocourse06/homework.go
> +func makeCages() [5]Cage {
`make` має особливе значення в Go
https://dave.cheney.net/2014/08/17/go-has-both-make-and-new-functions-what-gives


Функції, які починаються з `make`, створюють щось.

2024-09-24 19:37 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +	chanel chan<- bool
перейменував

2024-09-24 19:38 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +	fmt.Printf("Recived Feeder status: is full %t\n", feederState)
done

2024-09-24 19:39 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +	if cage.IsOpen == true {
спростив

2024-09-24 20:20 UTC, babenko-alex-pdffiller commented on gocourse06/homework.go
> +		cage.IsOpen = false
схоже на то, переробив

2024-09-25 11:28 UTC, alexandear requested changes

2024-09-25 11:28 UTC, alexandear commented on gocourse06/homework.go
> +package main
Виправ Data Race, будь ласка. Якщо запустити програму з флажком `-race` https://go.dev/doc/articles/race_detector, то отримаємо помилку виконання. 

<details><summary>Деталі</summary>
<p>

```
❯ go run -race homework.go
Collect data for Lion
Collect data for Monkey
Received Feeder status: is full false
Collect data for Zebra
Collect data for Giraffe
Collect data for Elephant
Received Feeder status: is full true
Cage #111 is open true
==================
WARNING: DATA RACE
Read at 0x00c00013c008 by goroutine 15:
  main.(*Cage).ToggleCageDoor.func1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse06/homework.go:28 +0x94

Previous write at 0x00c00013c008 by goroutine 11:
  main.(*Cage).ToggleCageDoor.func1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse06/homework.go:31 +0xbc

Goroutine 15 (running) created at:
  main.(*Cage).ToggleCageDoor()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse06/homework.go:26 +0xa4
  main.processData()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse06/homework.go:106 +0x474
  main.main()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse06/homework.go:63 +0x44

Goroutine 11 (running) created at:
  main.(*Cage).ToggleCageDoor()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse06/homework.go:26 +0xa4
Received Animal data: {Name:Lion Health:49 Hunger:44 State:Happy}
  main.processData()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse06/homework.go:85 +0x2ac
  main.main()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse06/homework.go:63 +0x44
==================
Received Animal data: {Name:Monkey Health:59 Hunger:42 State:Angry}
Received Animal data: {Name:Zebra Health:36 Hunger:76 State:Sad}
Cage #111 is open false
Received Animal data: {Name:Giraffe Health:13 Hunger:95 State:Happy}
Received Animal data: {Name:Elephant Health:54 Hunger:81 State:Angry}
All goroutines finished
Found 1 data race(s)
exit status 66
```

</p>
</details>

2024-09-26 11:52 UTC, alexandear approved these changes
LGMT

2024-10-14 12:49 UTC, merged