added hw07
babenko-alex-pdffiller/prjctr-golang pull request #2
Opened 2024-09-12 08:52 UTC by babenko-alex-pdffiller

2024-09-12 11:38 UTC, alexandear requested changes

2024-09-12 11:38 UTC, alexandear commented on gocourse07/homework.go
> +func main() {
Переглянь, будь ласка, в програмі є data races.

Я запускав через `go run -race .`. Про флажок `-race` описано https://go.dev/blog/race-detector. Також потрібно додати `go.mod` файл через `go mod init`, щоб запрацювало.

<details>
<summary>Деталі</summary>

```
❯ go run -race .
Sensor 2 sent data: 30
Sensor 1 sent data: 31
Sensor 3 sent data: 55
Central system added to memory 55
==================
WARNING: DATA RACE
Write at 0x00c0001a00c0 by goroutine 11:
  runtime.mapaccess2_faststr()
      /opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/map_faststr.go:117 +0x42c
  main.(*CentralSystem).Run.func1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:56 +0x120

Previous read at 0x00c0001a00c0 by goroutine 10:
  runtime.evacuate_fast64()
      /opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/map_fast64.go:407 +0x3dc
  main.(*CentralSystem).Run.func1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:55 +0xcc

Goroutine 11 (running) created at:
  main.(*CentralSystem).Run()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:53 +0x58
  main.main.gowrap2()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:92 +0x58

Goroutine 10 (running) created at:
  main.(*CentralSystem).Run()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:53 +0x58
  main.main.gowrap2()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:92 +0x58
==================
==================
WARNING: DATA RACE
Write at 0x00c0001a00c0 by goroutine 12:
  runtime.mapaccess2_faststr()
      /opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/map_faststr.go:117 +0x42c
  main.(*CentralSystem).Run.func1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:56 +0x120

Previous read at 0x00c0001a00c0 by goroutine 11:
  runtime.evacuate_fast64()
      /opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/map_fast64.go:407 +0x3dc
  main.(*CentralSystem).Run.func1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:58 +0x198

Goroutine 12 (running) created at:
  main.(*CentralSystem).Run()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:53 +0x58
  main.main.gowrap2()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:92 +0x58

Goroutine 11 (running) created at:
  main.(*CentralSystem).Run()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:53 +0x58
  main.main.gowrap2()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:92 +0x58
==================
Central system added to memory 30
Central system added to memory 31
Sensor 1 sent data: 78
Sensor 2 sent data: 81
Sensor 3 sent data: 94
==================
WARNING: DATA RACE
Read at 0x00c000102160 by goroutine 14:
  main.(*CentralSystem).Run.func1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:55 +0xd4

Previous write at 0x00c000102160 by goroutine 11:
  main.(*CentralSystem).Run.func1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:56 +0x12c

Goroutine 14 (running) created at:
  main.(*CentralSystem).Run()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:53 +0x58
  main.main.gowrap2()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:92 +0x58

Goroutine 11 (running) created at:
  main.(*CentralSystem).Run()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:53 +0x58
  main.main.gowrap2()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:92 +0x58
==================
==================
WARNING: DATA RACE
Write at 0x00c0001a0240 by goroutine 14:
  runtime.mapaccess2_fast64()
      /opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/map_fast64.go:62 +0x1cc
  main.(*CentralSystem).Run.func1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:58 +0x26c

Previous write at 0x00c0001a0240 by goroutine 11:
  runtime.mapaccess2_fast64()
      /opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/map_fast64.go:62 +0x1cc
  main.(*CentralSystem).Run.func1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:58 +0x26c

Goroutine 14 (running) created at:
  main.(*CentralSystem).Run()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:53 +0x58
  main.main.gowrap2()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:92 +0x58

Goroutine 11 (running) created at:
  main.(*CentralSystem).Run()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:53 +0x58
  main.main.gowrap2()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:92 +0x58
==================
Central system added to memory 81
Central system added to memory 94
Central system added to memory 78
Sensor 3 sent data: 54
Sensor 1 sent data: 96
Sensor 2 sent data: 31
Central system added to memory 96
Central system added to memory 54
Central system added to memory 31
Started technical maintenance
Central system shutting down, waiting for all records to be saved.
Sensor #1 Temperature stopped
Sensor #3 Humidity stopped
Sensor #2 Brightness stopped
Maintenance completed. System is shut down.
Sensor Humidity, time 1726140963644863000, data 55
Sensor Humidity, time 1726140964646738000, data 94
Sensor Humidity, time 1726140965646519000, data 54
Sensor Brightness, time 1726140963645213000, data 30
Sensor Brightness, time 1726140964645626000, data 81
Sensor Brightness, time 1726140965646505000, data 31
Sensor Temperature, time 1726140963645294000, data 31
Sensor Temperature, time 1726140964647056000, data 78
Sensor Temperature, time 1726140965646505000, data 96
Found 4 data race(s)
exit status 66
```

</details>

2024-09-26 20:25 UTC, babenko-alex-pdffiller commented on gocourse07/homework.go
> +func main() {
так, є data race - виправив

2024-09-28 13:08 UTC, alexandear requested changes

2024-09-28 13:08 UTC, alexandear commented on gocourse07/homework.go
> +func main() {
Новий data race, якщо запускати програму кілька разів.

<details><summary>Details</summary>
<p>

```
❯ go run -race .
Central system added to memory 14
Sensor Temperature sent data: 14
Central system added to memory 79
Sensor Brightness sent data: 69
Central system added to memory 69
Sensor Humidity sent data: 79
Sensor Brightness sent data: 30
Sensor Temperature sent data: 37
Central system added to memory 30
Sensor Humidity sent data: 67
Central system added to memory 37
Central system added to memory 67
Sensor Humidity sent data: 61
Sensor Brightness sent data: 35
Central system added to memory 61
Central system added to memory 35
Sensor Temperature sent data: 14
Central system added to memory 14
Started technical maintenance
Maintenance completed. System is shut down.
Sensor #1 Temperature stopped
Sensor #3 Humidity stopped
Sensor #2 Brightness stopped
Central system shutting down, waiting for all records to be saved.
Sensor Temperature, time 1727528795435581000, data 14
Sensor Temperature, time 1727528796437177000, data 37
Sensor Temperature, time 1727528797438564000, data 14
Sensor Humidity, time 1727528795435641000, data 79
Sensor Humidity, time 1727528796437202000, data 67
Sensor Humidity, time 1727528797438357000, data 61
Sensor Brightness, time 1727528796437064000, data 30
Sensor Brightness, time 1727528797438511000, data 35
Sensor Brightness, time 1727528795435658000, data 69
❯ go run -race .
Central system added to memory 56
Sensor Humidity sent data: 65
Central system added to memory 87
Sensor Brightness sent data: 56
Central system added to memory 65
Sensor Temperature sent data: 87
Sensor Temperature sent data: 20
Central system added to memory 20
Sensor Brightness sent data: 44
Central system added to memory 44
Sensor Humidity sent data: 29
Central system added to memory 29
Sensor Brightness sent data: 43
Sensor Humidity sent data: 37
Sensor Temperature sent data: 28
Central system added to memory 37
Central system added to memory 43
Central system added to memory 28
Started technical maintenance
Maintenance completed. System is shut down.
Sensor #1 Temperature stopped
Sensor #3 Humidity stopped
Sensor #2 Brightness stopped
Central system shutting down, waiting for all records to be saved.
fSensor Brightness, time 1727528804043592000, data 56
Sensor Brightness, time 1727528805045302000, data 44
Sensor Brightness, time 1727528806046778000, data 43
Sensor Temperature, time 1727528804043695000, data 87
Sensor Temperature, time 1727528805045257000, data 20
Sensor Temperature, time 1727528806046803000, data 28
Sensor Humidity, time 1727528804043717000, data 65
Sensor Humidity, time 1727528805045470000, data 29
Sensor Humidity, time 1727528806046559000, data 37
❯ go run -race .
Central system added to memory 40
Central system added to memory 61
Central system added to memory 27
Sensor Humidity sent data: 27
Sensor Temperature sent data: 61
Sensor Brightness sent data: 40
Sensor Temperature sent data: 91
Central system added to memory 73
Central system added to memory 91
Central system added to memory 58
Sensor Brightness sent data: 73
Sensor Humidity sent data: 58
Sensor Humidity sent data: 71
Sensor Temperature sent data: 37
Central system added to memory 37
Sensor Brightness sent data: 56
Central system added to memory 71
Central system added to memory 56
Started technical maintenance
Maintenance completed. System is shut down.
Sensor #2 Brightness stopped
Sensor #1 Temperature stopped
Sensor #3 Humidity stopped
Central system shutting down, waiting for all records to be saved.
Sensor Brightness, time 1727528812458606000, data 40
Sensor Brightness, time 1727528813460148000, data 73
Sensor Brightness, time 1727528814461465000, data 56
Sensor Temperature, time 1727528812458642000, data 61
Sensor Temperature, time 1727528813460231000, data 91
Sensor Temperature, time 1727528814461365000, data 37
Sensor Humidity, time 1727528812458671000, data 27
Sensor Humidity, time 1727528813460334000, data 58
Sensor Humidity, time 1727528814461417000, data 71
❯ go run -race .
Sensor Brightness sent data: 27
Sensor Temperature sent data: 17
Central system added to memory 27
Central system added to memory 56
Central system added to memory 17
Sensor Humidity sent data: 56
Sensor Humidity sent data: 96
Sensor Temperature sent data: 13
Central system added to memory 96
Central system added to memory 83
Central system added to memory 13
Sensor Brightness sent data: 83
Sensor Humidity sent data: 82
Central system added to memory 82
Central system added to memory 79
Central system added to memory 81
Sensor Brightness sent data: 81
Sensor Temperature sent data: 79
Started technical maintenance
Maintenance completed. System is shut down.
Sensor #3 Humidity stopped
Sensor #1 Temperature stopped
==================
WARNING: DATA RACE
Read at 0x00c000090038 by goroutine 7:
  runtime.raceread()
      <autogenerated>:1 +0x10
  main.(*Sensor).Run()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:22 +0x1cc
  main.main.gowrap1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:86 +0x64

Previous write at 0x00c000090038 by goroutine 9:
  runtime.racewrite()
      <autogenerated>:1 +0x10
  main.(*CentralSystem).Run()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:50 +0x2fc
  main.main.gowrap2()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:89 +0x58

Goroutine 7 (running) created at:
  main.main()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:86 +0x228

Goroutine 9 (running) created at:
  main.main()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:89 +0x448
==================
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 21 [running]:
sync.(*WaitGroup).Wait(0xc000090030)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/sync/waitgroup.go:120 +0xe0
main.(*CentralSystem).Run(0xc0000b0000, {0x100886a58, 0xc0000b2000}, 0xc0000ac000)
        /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:50 +0x300
created by main.main in goroutine 1
        /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse07/homework.go:89 +0x44c
exit status 2
```

</p>
</details>

2024-10-16 08:40 UTC, alexandear approved these changes

2024-10-16 12:57 UTC, merged