add hw08
babenko-alex-pdffiller/prjctr-golang pull request #3
Opened 2024-09-13 14:09 UTC by babenko-alex-pdffiller

2024-09-13 15:00 UTC, alexandear requested changes

2024-09-13 15:00 UTC, alexandear commented on gocourse08/homework.go
> +func main() {
Якщо запустити програму `go run -race homework.go`, то отримаємо стан гонки. Будь ласка, пофікси це.

<details><summary>Деталі</summary>
<p>

```
❯ go run -race homework.go

bear
cat
primat
Gprs unactive, save data to local: {Kind:bear Pulse:48 Temperature:37.5 Breathing:11 Sound:roar}
Gprs unactive, save data to local: {Kind:cat Pulse:160 Temperature:38.5 Breathing:58 Sound:meow}
Gprs unactive, save data to local: {Kind:primat Pulse:50 Temperature:36.5 Breathing:53 Sound:scream}
==================
WARNING: DATA RACE
Write at 0x00c000138018 by main goroutine:
  main.(*Sender).ActivateGprs()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse08/homework.go:93 +0xab0
  main.main()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse08/homework.go:116 +0xaa8

Previous read at 0x00c000138018 by goroutine 6:
  main.(*Sender).Send()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse08/homework.go:73 +0x78
  main.main.gowrap1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse08/homework.go:108 +0x40

Goroutine 6 (running) created at:
  main.main()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse08/homework.go:108 +0x9c8
==================
==================
WARNING: DATA RACE
Read at 0x00c000138000 by main goroutine:
  main.(*Sender).SendAllData()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse08/homework.go:84 +0x48
  main.main()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse08/homework.go:117 +0xac4

Previous write at 0x00c000138000 by goroutine 6:
  main.(*Sender).Send()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse08/homework.go:77 +0x244
  main.main.gowrap1()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse08/homework.go:108 +0x40

Goroutine 6 (running) created at:
  main.main()
      /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse08/homework.go:108 +0x9c8
==================
Send local data: {Kind:bear Pulse:48 Temperature:37.5 Breathing:11 Sound:roar}
Sending data for bear: {Kind:bear Pulse:48 Temperature:37.5 Breathing:11 Sound:roar}
Send local data: {Kind:cat Pulse:160 Temperature:38.5 Breathing:58 Sound:meow}
Send local data: {Kind:primat Pulse:50 Temperature:36.5 Breathing:53 Sound:scream}
Sending data for cat: {Kind:cat Pulse:160 Temperature:38.5 Breathing:58 Sound:meow}
Sending data for primat: {Kind:primat Pulse:50 Temperature:36.5 Breathing:53 Sound:scream}
Found 2 data race(s)
exit status 66
```

</p>
</details>

2024-09-13 15:00 UTC, alexandear commented on gocourse08/homework.go
> +func main() {
Про Race Detector https://go.dev/doc/articles/race_detector

2024-10-14 14:41 UTC, babenko-alex-pdffiller commented on gocourse08/homework.go
> +func main() {
так, дісно, виправив

2024-10-14 15:06 UTC, alexandear approved these changes
LGTM

2024-10-16 07:29 UTC, merged