add HW09
babenko-alex-pdffiller/prjctr-golang pull request #4
Opened 2024-09-17 19:57 UTC by babenko-alex-pdffiller

2024-09-18 17:33 UTC, alexandear requested changes

2024-09-18 17:33 UTC, alexandear commented on gocourse09/homework_test.go
> +package main
Тести рандомно не проходять, якщо запускати багато разів. Ось, наприклад, фейл:
```
=== RUN   TestCalculateFoods
--- PASS: TestCalculateFoods (0.00s)
=== RUN   TestGiveOut
Issued out banana in 3 portions
Issued out meat in 2 portions
Issued out millet in 4 portions
Issued out porridge in 1 portions
--- PASS: TestGiveOut (0.00s)
=== RUN   TestMoveAnimalsPosition
Animals moved
    /Users/Oleksandr_Redko/src/github.com/babenko-alex-pdffiller/prjctr-golang/gocourse09/homework_test.go:102: Animal with ID 4 did not change its position
--- FAIL: TestMoveAnimalsPosition (0.00s)
FAIL
coverage: 43.2% of statements
FAIL	gocourse09	0.357s
```

2024-09-18 17:33 UTC, alexandear commented on gocourse09/homework.go
Чи можемо додати файл `go.mod` з назвою модуля? Ці знання про go.mod пригодяться для курсової та реальних проектів. Підказка: використовувати команду `go mod init`


Має бути щось таке:
```go
module github.com/babenko-alex-pdffiller/prjctr-golang/gocourse09

go 1.23.0
```

2024-09-18 17:33 UTC, alexandear commented on gocourse09/homework.go
> +	for i, _ := range animals {
можна спростити:
```suggestion
	for i := range animals {
```

2024-09-18 17:33 UTC, alexandear commented on gocourse09/homework.go
> +		animals[i].Position = rand.IntN(20) + 1
Що буде, коли дві тварини матимуть однаковий `Position`? Здається, це можливо в даній реалізації.

2024-09-18 17:33 UTC, alexandear commented on gocourse09/homework_test.go
> +		}
Пропоную спростити за допомогою пакету [`slices`](https://pkg.go.dev/slices#ContainsFunc):
```suggestion
		expected := slices.ContainsFunc(nearAnimals, func(animal Animal) bool {
			return animal.ID == expectedAnimal.ID
		})
```

2024-09-18 17:33 UTC, alexandear commented on gocourse09/homework_test.go
> +			t.Errorf("Animal %v not found in nearAnimals", expectedAnimal)
Для полегшення можливого дебагінгу пропоную додати `nearAnimals` у вивід:
```suggestion
			t.Errorf("Animal %v not found in nearAnimals %v", expectedAnimal, nearAnimals)
```

2024-09-25 11:33 UTC, alexandear commented on gocourse09/homework_test.go
> +package main
Тести все ще інколи фейляться:

```
❯ go test -race -v -count=1 -parallel=4 ./...
=== RUN   TestGiveOut
Issued out banana in 3 portions
Issued out meat in 2 portions
Issued out millet in 4 portions
Issued out porridge in 1 portions
--- PASS: TestGiveOut (0.00s)
=== RUN   TestCalculateFoods
--- PASS: TestCalculateFoods (0.00s)
=== RUN   TestFindAnimalsNear
Found near Gorilla
Found near Duck
Found near Swan
--- PASS: TestFindAnimalsNear (0.00s)
=== RUN   TestMoveAnimalsPosition
Animals moved
    homework_test.go:102: Animal with ID 2 did not change its position
    homework_test.go:102: Animal with ID 20 did not change its position
--- FAIL: TestMoveAnimalsPosition (0.00s)
FAIL
FAIL    gocourse09      0.259s
FAIL
```

Запускати так: `go test -race -v -count=1 -parallel=4 ./...`

2024-10-14 16:11 UTC, babenko-alex-pdffiller commented on gocourse09/homework.go
додав `go.mod` через init саме в папку gocourse09, і почало видавати помилку на рівні тесту. Це тре зробити окремо для gocourse09? Бо в корні є загальний `go.mod`.

2024-10-14 16:17 UTC, babenko-alex-pdffiller commented on gocourse09/homework.go
> +		animals[i].Position = rand.IntN(20) + 1
саме так, `Position` - досить умовний в даному випадку, + в умові не має обмежень на кількість тварин в 1 місці

2024-10-14 16:53 UTC, babenko-alex-pdffiller commented on gocourse09/homework_test.go
> +		}
використав

2024-10-14 16:54 UTC, babenko-alex-pdffiller commented on gocourse09/homework_test.go
> +			t.Errorf("Animal %v not found in nearAnimals", expectedAnimal)
додав

2024-10-17 07:33 UTC, alexandear commented on gocourse09/homework.go
В корені немає загального `go.mod`.

https://github.com/babenko-alex-pdffiller/prjctr-golang/tree/HW09


Все, що я бачу

<img width="950" alt="image" src="https://github.com/user-attachments/assets/719914dd-b527-48f6-a5a8-8dfc3149309f">

2024-10-17 08:20 UTC, alexandear approved these changes

2024-10-17 16:38 UTC, merged